'use strict';

const IMG_BASE = 'watch_crops_named/';

const PRODUCTS = [
  { id:1, name:"Miracle Langbo Fancy Chain", brand:"Miracle", category:"ladies", style:"chain", costPrice:575, costPriceMax:675, sellPrice:1150, sellPriceMax:1350, images:["Miracle_Langbo_Fancy_chain_575-675.jpg"], description:"Elegant fancy chain style ladies watch with intricate design. A perfect accessory for any occasion.", featured:false, isNew:true, inStock:true, rating:4.5, reviews:8 },
  { id:2, name:"Miracle 3022 PU Ladies Band", brand:"Miracle", category:"ladies", style:"casual", costPrice:450, sellPrice:900, images:["Miracle_3022_PU_LB_450.jpg"], description:"Comfortable PU strap ladies watch with a classic round dial. Great for everyday wear.", featured:false, isNew:false, inStock:true, rating:4.2, reviews:15 },
  { id:3, name:"Panda PU Ladies Band", brand:"Panda", category:"ladies", style:"casual", costPrice:250, sellPrice:500, images:["Panda_PU_LB_250.jpg"], description:"Stylish and affordable PU strap ladies watch. Perfect for casual daily use.", featured:false, isNew:false, inStock:true, rating:4.0, reviews:22 },
  { id:4, name:"Miracle M83", brand:"Miracle", category:"gents", style:"casual", costPrice:675, sellPrice:1350, images:["Miracle_M83_675.jpg"], description:"Classic gents watch with a timeless design. Durable build with a comfortable fit.", featured:false, isNew:false, inStock:true, rating:4.3, reviews:18 },
  { id:5, name:"Miracle M01", brand:"Miracle", category:"gents", style:"classic", costPrice:950, sellPrice:1900, images:["Miracle_M01_950.jpg"], description:"Premium gents watch with a sophisticated look. Features a clear dial and reliable movement.", featured:true, isNew:false, inStock:true, rating:4.7, reviews:35 },
  { id:6, name:"Repeat Ladies Band", brand:"Repeat", category:"ladies", style:"casual", costPrice:250, sellPrice:500, images:["Repeat_LB_250.jpg"], description:"Lightweight ladies band watch that combines simplicity with charm.", featured:false, isNew:false, inStock:true, rating:3.9, reviews:10 },
  { id:7, name:"Miracle M02", brand:"Miracle", category:"gents", style:"classic", costPrice:950, sellPrice:1900, images:["Miracle_M02_950.jpg"], description:"Stylish gents watch with a bold dial design and premium build quality.", featured:false, isNew:false, inStock:true, rating:4.6, reviews:28 },
  { id:8, name:"Miracle Bangle Watch", brand:"Miracle", category:"ladies", style:"bangle", costPrice:900, sellPrice:1800, images:["Miracle_Bangle_900.jpg"], description:"Stunning bangle-style ladies watch that doubles as an elegant bracelet.", featured:true, isNew:false, inStock:true, rating:4.8, reviews:42 },
  { id:9, name:"Omega Gents 086", brand:"Omega", category:"gents", style:"classic", costPrice:1000, sellPrice:2000, images:["Omega_Gents_086_1000.jpg"], description:"Premium Omega-style gents watch with sophisticated design. Exudes class and confidence.", featured:true, isNew:false, inStock:true, rating:4.9, reviews:56 },
  { id:10, name:"Omega Ladies 086", brand:"Omega", category:"ladies", style:"classic", costPrice:1000, sellPrice:2000, images:["Omega_Ladies_086_1000.jpg"], description:"Elegant Omega-style ladies watch with a refined design. The perfect gift for her.", featured:true, isNew:false, inStock:true, rating:4.9, reviews:48 },
  { id:11, name:"Miracle M083 Ladies", brand:"Miracle", category:"ladies", style:"casual", costPrice:675, sellPrice:1350, images:["Miracle_M083_Ladies_675.jpg"], description:"Graceful ladies watch with a comfortable strap and clear face. Ideal for everyday elegance.", featured:false, isNew:false, inStock:true, rating:4.4, reviews:20 },
  { id:12, name:"Miracle M83 Gents", brand:"Miracle", category:"gents", style:"casual", costPrice:675, sellPrice:1350, images:["Miracle_M83_Gents_675.jpg"], description:"Reliable gents watch with a bold face and comfortable band.", featured:false, isNew:false, inStock:true, rating:4.4, reviews:17 },
  { id:13, name:"Miracle Cut Glass Gents", brand:"Miracle", category:"gents", style:"classic", costPrice:1000, sellPrice:2000, images:["Miracle_Cut_Glass_Gents_1000.jpg"], description:"Luxurious cut glass gents watch with a stunning prismatic effect. A true collector's piece.", featured:true, isNew:false, inStock:true, rating:4.8, reviews:32 },
  { id:14, name:"Miracle Cut Glass Ladies", brand:"Miracle", category:"ladies", style:"classic", costPrice:1000, sellPrice:2000, images:["Miracle_Cut_Glass_Ladies_1000.jpg"], description:"Breathtaking cut glass ladies watch that catches the light beautifully. Elegance redefined.", featured:true, isNew:false, inStock:true, rating:4.8, reviews:29 },
  { id:15, name:"Miracle M080 Gents", brand:"Miracle", category:"gents", style:"casual", costPrice:900, sellPrice:1800, images:["Miracle_M080_Gents_900.jpg"], description:"Smart casual gents watch with a modern dial design and durable construction.", featured:false, isNew:false, inStock:true, rating:4.5, reviews:24 },
  { id:16, name:"Nurse Watch", brand:"Nurse", category:"ladies", style:"casual", costPrice:275, sellPrice:550, images:["Nurse_Watch_275.jpg"], description:"Classic nurse/pocket watch with a clean white dial. Perfect for medical professionals.", featured:false, isNew:false, inStock:true, rating:4.1, reviews:38 },
  { id:17, name:"Miracle Open Bangle Classic", brand:"Miracle", category:"ladies", style:"bangle", costPrice:750, sellPrice:1500, images:["Miracle_Open_Bangle_750.jpg"], description:"Beautifully crafted open bangle watch. Adjustable fit with timeless appeal.", featured:false, isNew:false, inStock:true, rating:4.6, reviews:19 },
  { id:18, name:"Miracle Open Bangle Premium", brand:"Miracle", category:"ladies", style:"bangle", costPrice:800, sellPrice:1600, images:["Miracle_Open_Bangle_800.jpg","Miracle_Open_Bangle_800_2.jpg"], description:"Premium open bangle watch with exquisite detailing. Multiple designs available.", featured:false, isNew:true, inStock:true, rating:4.7, reviews:26 },
  { id:19, name:"Miracle M080 Ladies", brand:"Miracle", category:"ladies", style:"casual", costPrice:900, sellPrice:1800, images:["Miracle_M080_Ladies_900.jpg"], description:"Stylish ladies watch with contemporary design. Perfectly balances fashion and function.", featured:false, isNew:false, inStock:true, rating:4.5, reviews:21 },
  { id:20, name:"Miracle M033 Ladies", brand:"Miracle", category:"ladies", style:"casual", costPrice:900, sellPrice:1800, images:["Miracle_M033_Ladies_900.jpg"], description:"Chic ladies watch with a modern aesthetic. Water-resistant with a classic round case.", featured:false, isNew:false, inStock:true, rating:4.4, reviews:16 },
  { id:21, name:"Miracle Colour Square Small", brand:"Miracle", category:"ladies", style:"casual", costPrice:450, sellPrice:900, images:["Miracle_Colour_Square_Small_450.jpg"], description:"Trendy square-faced ladies watch with vibrant colour options. Fun and fashionable.", featured:false, isNew:false, inStock:true, rating:4.2, reviews:13 },
  { id:22, name:"Rolex Open Bangle", brand:"Rolex", category:"ladies", style:"bangle", costPrice:850, sellPrice:1700, images:["Rolex_Open_Bangle_850.jpg","Rolex_Open_Bangle_850_2.jpg","Rolex_Open_Bangle_850_3.jpg"], description:"Luxurious Rolex-inspired open bangle watch. Available in multiple stunning finishes.", featured:true, isNew:false, inStock:true, rating:4.8, reviews:67 },
  { id:23, name:"Miracle M040", brand:"Miracle", category:"gents", style:"casual", costPrice:900, sellPrice:1800, images:["Miracle_M040_900.jpg"], description:"Sleek gents watch with a minimalist dial and quality build. Understated elegance.", featured:false, isNew:false, inStock:true, rating:4.3, reviews:14 },
  { id:24, name:"Rado Ra03", brand:"Rado", category:"gents", style:"classic", costPrice:900, sellPrice:1800, images:["Rado_Ra03_900.jpg"], description:"Premium Rado-inspired gents watch with a refined Swiss-style design. Sophisticated luxury.", featured:false, isNew:false, inStock:true, rating:4.6, reviews:31 },
  { id:25, name:"Miracle M037", brand:"Miracle", category:"gents", style:"casual", costPrice:800, sellPrice:1600, images:["Miracle_M037_800.jpg","Miracle_M037_800_2.jpg"], description:"Modern gents watch with a clean design. Multiple dial variants available.", featured:false, isNew:false, inStock:true, rating:4.4, reviews:22 },
  { id:26, name:"Miracle Smart Ladies Band 123", brand:"Miracle", category:"ladies", style:"casual", costPrice:600, sellPrice:1200, images:["Miracle_Smart_LB_123_600.jpg"], description:"Smart design ladies band watch with an attractive dial. A stylish everyday companion.", featured:false, isNew:true, inStock:true, rating:4.3, reviews:27 },
  { id:27, name:"Mountblanc Chronograph", brand:"Mountblanc", category:"gents", style:"sport", costPrice:1000, sellPrice:2000, images:["Mountblanc_Cron_1000.jpg"], description:"Premium Mountblanc-inspired chronograph watch. Bold, sporty design with multiple functions.", featured:true, isNew:false, inStock:true, rating:4.8, reviews:44 },
  { id:28, name:"Miracle M59", brand:"Miracle", category:"gents", style:"casual", costPrice:900, sellPrice:1800, images:["Miracle_M59_900.jpg"], description:"Classic gents watch combining traditional craftsmanship with contemporary styling.", featured:false, isNew:false, inStock:true, rating:4.4, reviews:19 },
  { id:29, name:"Miracle M031 Ladies", brand:"Miracle", category:"ladies", style:"casual", costPrice:800, costPriceMax:900, sellPrice:1600, sellPriceMax:1800, images:["Miracle_ladies_M031_800-900.jpg"], description:"Elegant ladies watch available in two premium variants. Timeless design for the modern woman.", featured:false, isNew:false, inStock:true, rating:4.5, reviews:23 },
  { id:30, name:"Miracle M031 Gents", brand:"Miracle", category:"gents", style:"casual", costPrice:800, costPriceMax:900, sellPrice:1600, sellPriceMax:1800, images:["Miracle_Gents_M031_800-900.jpg"], description:"Distinguished gents watch available in two premium variants. Classic style with modern precision.", featured:false, isNew:false, inStock:true, rating:4.5, reviews:20 },
  { id:31, name:"Miracle M056 Bangle", brand:"Miracle", category:"ladies", style:"bangle", costPrice:900, sellPrice:1800, images:["Miracle_M056_Bangle_900.jpg"], description:"Sophisticated bangle watch with a jewellery-inspired design. A wrist-wear statement piece.", featured:false, isNew:false, inStock:true, rating:4.6, reviews:17 },
  { id:32, name:"Miracle PU Sport Ladies Band", brand:"Miracle", category:"ladies", style:"sport", costPrice:675, sellPrice:1350, images:["Miracle_PU_Sport_Lb_675.jpg"], description:"Sporty ladies watch with a durable PU strap. Active and fashionable for all lifestyles.", featured:false, isNew:true, inStock:true, rating:4.3, reviews:21 },
  { id:33, name:"Miracle Ladies Open Bangle", brand:"Miracle", category:"ladies", style:"bangle", costPrice:800, sellPrice:1600, images:["Miracle_Ladies_Open_Bangle_800.jpg"], description:"Graceful open bangle watch designed exclusively for women. Delicate yet durable.", featured:false, isNew:false, inStock:true, rating:4.5, reviews:16 },
  { id:34, name:"Miracle M51", brand:"Miracle", category:"gents", style:"casual", costPrice:900, sellPrice:1800, images:["Miracle_M51_900.jpg"], description:"Sharp-looking gents watch with a contemporary dial. A reliable timepiece for the modern man.", featured:false, isNew:false, inStock:true, rating:4.4, reviews:25 },
  { id:35, name:"Miracle Apple Ladies Band", brand:"Miracle", category:"ladies", style:"casual", costPrice:450, sellPrice:900, images:["Miracle_Apple_LB_450.jpg"], description:"Fun apple-inspired ladies watch with a playful design. Trendy and affordable.", featured:false, isNew:true, inStock:true, rating:4.2, reviews:31 },
  { id:36, name:"Miracle M041 Ladies Band", brand:"Miracle", category:"ladies", style:"casual", costPrice:650, sellPrice:1300, images:["Miracle_M041_LB_650.jpg"], description:"Chic ladies band watch with a clean dial design. Perfect balance of style and comfort.", featured:false, isNew:false, inStock:true, rating:4.4, reviews:14 },
  { id:37, name:"Skemi SK01", brand:"Skemi", category:"gents", style:"classic", costPrice:600, sellPrice:1200, images:["Skemi_SK01_600.jpg"], description:"Quality Skemi gents watch with a clear dial and durable construction. Dependable timekeeper.", featured:false, isNew:false, inStock:true, rating:4.3, reviews:29 },
  { id:38, name:"Miracle M60 Open Bangle", brand:"Miracle", category:"ladies", style:"bangle", costPrice:800, sellPrice:1600, images:["Miracle_M60_Open_Bangle_800.jpg"], description:"Exquisite M60 open bangle watch with a refined finish. A seamless fusion of time and fashion.", featured:false, isNew:false, inStock:true, rating:4.5, reviews:18 },
  { id:39, name:"MK Bangle Watch", brand:"MK", category:"ladies", style:"bangle", costPrice:500, sellPrice:1000, images:["MK_Bangle_500.jpg","MK_Bangle_500_2.jpg","MK_Bangle_500_3.jpg","MK_Bangle_500_4.jpg","MK_Bangle_500_5.jpg","MK_Bangle_500_6.jpg"], description:"Gorgeous MK bangle watch available in 6 stunning colour variants. Fashion meets function.", featured:true, isNew:false, inStock:true, rating:4.7, reviews:53 },
  { id:40, name:"Rado Copper DD", brand:"Rado", category:"gents", style:"classic", costPrice:675, sellPrice:1350, images:["Rado_Copper_DD_675.jpg"], description:"Striking Rado-inspired copper-toned double date gents watch. Unique and sophisticated.", featured:false, isNew:false, inStock:true, rating:4.5, reviews:27 },
  { id:41, name:"Swish Ladies", brand:"Swish", category:"ladies", style:"classic", costPrice:1000, sellPrice:2000, images:["Swish_Ladies_1000.jpg"], description:"Premium Swish ladies watch with a classic design and superior finish. Timeless luxury.", featured:false, isNew:false, inStock:true, rating:4.7, reviews:38 },
  { id:42, name:"Miracle M036", brand:"Miracle", category:"ladies", style:"casual", costPrice:900, sellPrice:1800, images:["Miracle_M036_900.jpg"], description:"Stylish Miracle M036 ladies watch with a refined dial and comfortable strap.", featured:false, isNew:false, inStock:true, rating:4.4, reviews:15 },
  { id:43, name:"Swish Ladies DD", brand:"Swish", category:"ladies", style:"classic", costPrice:1000, sellPrice:2000, images:["Swish_Ladies_DD_1000.jpg"], description:"Elegant Swish double date ladies watch. Premium quality with a sleek sophisticated look.", featured:false, isNew:true, inStock:true, rating:4.7, reviews:32 },
  { id:44, name:"Miracle M052 Ladies", brand:"Miracle", category:"ladies", style:"casual", costPrice:900, sellPrice:1800, images:["Miracle_M052_Ladies_900.jpg"], description:"Contemporary Miracle M052 ladies watch with an attractive round case and clear dial.", featured:false, isNew:false, inStock:true, rating:4.5, reviews:19 },
  { id:45, name:"Miracle M081 Ladies DD", brand:"Miracle", category:"ladies", style:"casual", costPrice:575, costPriceMax:675, sellPrice:1150, sellPriceMax:1350, images:["Miracle_M081_Ladies_DD_575-675.jpg"], description:"Ladies double date watch in two premium variants. Practical and stylish.", featured:false, isNew:false, inStock:true, rating:4.3, reviews:22 },
  { id:46, name:"Miracle M081 Gents DD", brand:"Miracle", category:"gents", style:"casual", costPrice:575, costPriceMax:675, sellPrice:1150, sellPriceMax:1350, images:["Miracle_M081_Gents_DD_575-675.jpg"], description:"Gents double date watch available in two premium variants. Functionality meets style.", featured:false, isNew:false, inStock:true, rating:4.3, reviews:18 },
  { id:47, name:"Miracle M87 Ladies DD", brand:"Miracle", category:"ladies", style:"classic", costPrice:950, sellPrice:1900, images:["Miracle_M87_Ladies_DD_950.jpg"], description:"Sophisticated ladies double date watch with premium dial and quality construction.", featured:false, isNew:true, inStock:true, rating:4.6, reviews:24 },
  { id:48, name:"R15 Gents", brand:"R15", category:"gents", style:"sport", costPrice:1000, sellPrice:2000, images:["R15_Gents_1000.jpg","R15_Gents_1000_2.jpg"], description:"Bold R15 gents watch with a sporty aesthetic. Strong design for the active man.", featured:false, isNew:false, inStock:true, rating:4.6, reviews:33 },
  { id:49, name:"Miracle M006 Squire", brand:"Miracle", category:"gents", style:"classic", costPrice:900, sellPrice:1800, images:["Miracle_M006_Squire_900.jpg"], description:"Distinguished square-case gents watch with a classic appeal. Precision and elegance combined.", featured:false, isNew:false, inStock:true, rating:4.5, reviews:27 },
  { id:50, name:"Swish Gents", brand:"Swish", category:"gents", style:"classic", costPrice:1000, sellPrice:2000, images:["Swish_Gents_1000.jpg","Swish_Gents_1000_2.jpg"], description:"Premium Swish gents watch with excellent finish and quality movement. Available in two styles.", featured:false, isNew:false, inStock:true, rating:4.7, reviews:41 },
  { id:51, name:"Rolex Heavy Chain", brand:"Rolex", category:"gents", style:"chain", costPrice:1200, sellPrice:2400, images:["Rolex_Heavy_Chain_1200.jpg","Rolex_Heavy_Chain_1200_2.jpg"], description:"Iconic Rolex-inspired heavy chain gents watch. Bold statement of luxury and prestige.", featured:true, isNew:false, inStock:true, rating:4.9, reviews:72 },
  { id:52, name:"Swish Heavy", brand:"Swish", category:"gents", style:"classic", costPrice:1000, sellPrice:2000, images:["Swish_Heavy_1000.jpg","Swish_Heavy_1000_2.jpg"], description:"Heavy-duty Swish gents watch with a robust build. Built for the man who commands respect.", featured:false, isNew:false, inStock:true, rating:4.6, reviews:29 },
  { id:53, name:"Citizen", brand:"Citizen", category:"gents", style:"classic", costPrice:1300, sellPrice:2600, images:["Citizen_1300.jpg"], description:"Premium Citizen-inspired gents watch with exceptional quality. A timepiece of distinction.", featured:true, isNew:false, inStock:true, rating:4.9, reviews:88 },
  { id:54, name:"Binbond DD", brand:"Binbond", category:"gents", style:"sport", costPrice:900, sellPrice:1800, images:["Binbond_DD_900.jpg"], description:"Sporty Binbond double date gents watch with a bold design. Rugged and reliable.", featured:false, isNew:false, inStock:true, rating:4.4, reviews:26 },
  { id:55, name:"Hublot", brand:"Hublot", category:"gents", style:"luxury", costPrice:1300, sellPrice:2600, images:["Hublot_1300.jpg"], description:"The crown jewel of our collection. Hublot-inspired luxury watch with unrivalled design.", featured:true, isNew:false, inStock:true, rating:5.0, reviews:95 },
  { id:56, name:"Binbond", brand:"Binbond", category:"gents", style:"sport", costPrice:900, sellPrice:1800, images:["Binbond_900.jpg"], description:"Dependable Binbond gents watch with a striking design. Sporty precision for every day.", featured:false, isNew:false, inStock:true, rating:4.4, reviews:22 },
  { id:57, name:"Miracle Square Chain", brand:"Miracle", category:"gents", style:"chain", costPrice:850, sellPrice:1700, images:["Miracle_Square_Chain_850.jpg"], description:"Sophisticated square-case gents watch on a premium chain band. Unique and masculine.", featured:false, isNew:false, inStock:true, rating:4.5, reviews:19 },
  { id:58, name:"Miracle Square F Chain", brand:"Miracle", category:"gents", style:"chain", costPrice:850, sellPrice:1700, images:["Miracle_Square_F_Chain_850.jpg"], description:"Premium F-style square chain gents watch. A fusion of classic design and modern flair.", featured:false, isNew:false, inStock:true, rating:4.5, reviews:16 },
  { id:59, name:"Crono Chain", brand:"Crono", category:"gents", style:"chain", costPrice:1100, sellPrice:2200, images:["Crono_Chain_1100.jpg"], description:"Impressive Crono chain gents watch with chronograph-inspired dial. Power and prestige.", featured:false, isNew:true, inStock:true, rating:4.7, reviews:34 },
  { id:60, name:"Rado R70", brand:"Rado", category:"gents", style:"classic", costPrice:675, sellPrice:1350, images:["Rado_R70_675.jpg"], description:"Classic Rado R70 gents watch with a refined dial. Elegant Swiss-inspired design.", featured:false, isNew:false, inStock:true, rating:4.5, reviews:28 },
  { id:61, name:"Rolex R86", brand:"Rolex", category:"gents", style:"classic", costPrice:1000, sellPrice:2000, images:["Rolex_R86_1000.jpg"], description:"Iconic Rolex R86 gents watch. Prestigious design that speaks volumes about the wearer.", featured:true, isNew:false, inStock:true, rating:4.9, reviews:61 },
  { id:62, name:"Miracle M55 Bangle", brand:"Miracle", category:"ladies", style:"bangle", costPrice:800, sellPrice:1600, images:["Miracle_M55_Bangle_800.jpg"], description:"Gorgeous M55 bangle watch with a sparkling design. The ultimate feminine accessory.", featured:false, isNew:false, inStock:true, rating:4.6, reviews:21 },
  { id:63, name:"Miracle Couper DD", brand:"Miracle", category:"gents", style:"classic", costPrice:675, sellPrice:1350, images:["Miracle_Couper_DD_675.jpg"], description:"Refined Miracle Couper double date gents watch with clean aesthetic and reliable movement.", featured:false, isNew:false, inStock:true, rating:4.4, reviews:17 },
  { id:64, name:"N.F Fancy Chain", brand:"NF", category:"gents", style:"chain", costPrice:800, sellPrice:1600, images:["N.F_Fancy_Chain_800.jpg"], description:"Eye-catching NF fancy chain gents watch. Bold and distinctive for the fashion-forward man.", featured:false, isNew:false, inStock:true, rating:4.4, reviews:20 },
  { id:65, name:"Miracle M039", brand:"Miracle", category:"ladies", style:"casual", costPrice:875, sellPrice:1750, images:["Miracle_M039_875.jpg"], description:"Charming Miracle M039 ladies watch with an elegant design. Beautifully crafted for her.", featured:false, isNew:false, inStock:true, rating:4.5, reviews:15 },
  { id:66, name:"Miracle M032", brand:"Miracle", category:"ladies", style:"casual", costPrice:575, sellPrice:1150, images:["Miracle_M032_575.jpg"], description:"Petite Miracle M032 ladies watch with a feminine dial. Subtle elegance for everyday wear.", featured:false, isNew:false, inStock:true, rating:4.2, reviews:12 },
  { id:67, name:"Orvin Bangle", brand:"Orvin", category:"ladies", style:"bangle", costPrice:1000, sellPrice:2000, images:["Orvin_Bangle_1000.jpg","Orvin_Bangle_1000_2.jpg","Orvin_Bangle_1000_3.jpg","Orvin_Bangle_1000_4.jpg","Orvin_Bangle_1000_5.jpg","Orvin_Bangle_1000_6.jpg","Orvin_Bangle_1000_7.jpg","Orvin_Bangle_1000_8.jpg","Orvin_Bangle_1000_9.jpg"], description:"Magnificent Orvin bangle watch available in 9 gorgeous designs. Luxury redefined for women.", featured:true, isNew:true, inStock:true, rating:4.8, reviews:62 },
  { id:68, name:"Miracle Fancy Chain", brand:"Miracle", category:"ladies", style:"chain", costPrice:875, sellPrice:1750, images:["Miracle_Fancy_Chain_875.jpg"], description:"Luxurious fancy chain ladies watch with a glamorous design. Effortless sophistication.", featured:false, isNew:false, inStock:true, rating:4.6, reviews:23 },
  { id:69, name:"NF N02 Ladies", brand:"NF", category:"ladies", style:"casual", costPrice:900, sellPrice:1800, images:["NF_N02_Ladies_900.jpg"], description:"Stylish NF N02 ladies watch with a contemporary design. Quality and style at its best.", featured:false, isNew:false, inStock:true, rating:4.5, reviews:18 },
  { id:70, name:"MR Colour Ladies Band", brand:"MR", category:"ladies", style:"casual", costPrice:500, sellPrice:1000, images:["MR_Colour_LB_500.jpg"], description:"Vibrant MR colour ladies band watch. Expressive and fun for the fashionable woman.", featured:false, isNew:false, inStock:true, rating:4.2, reviews:26 },
  { id:71, name:"Lasika Big Smart Digital", brand:"Lasika", category:"digital", style:"digital", costPrice:350, sellPrice:700, images:["Lasika_Big_smart_Digital_350.jpg"], description:"Large-face Lasika smart digital watch with multiple functions. Perfect for active lifestyles.", featured:false, isNew:true, inStock:true, rating:4.3, reviews:45 },
  { id:72, name:"Lasika Digital", brand:"Lasika", category:"digital", style:"digital", costPrice:325, sellPrice:650, images:["Lasika_Digital_325.jpg","Lasika_Digital_325_2.jpg","Lasika_Digital_325_3.jpg","Lasika_Digital_325_4.jpg","Lasika_Digital_325_5.jpg","Lasika_Digital_325_6.jpg","Lasika_Digital_325_7.jpg","Lasika_Digital_325_8.jpg","Lasika_Digital_325_9.jpg","Lasika_Digital_325_10.jpg"], description:"Popular Lasika digital watch in 10 colour variants. Water-resistant with multiple display modes.", featured:false, isNew:false, inStock:true, rating:4.2, reviews:88 },
  { id:73, name:"Colour Box Medium", brand:"SS Collections", category:"accessories", style:"accessory", costPrice:250, sellPrice:500, images:["Colour_Box_Medium_250.jpg","Colour_Box_Medium_250_2.jpg","Colour_Box_Medium_250_3.jpg"], description:"Beautiful colourful watch gift box in medium size. Perfect presentation for gifting a watch.", featured:false, isNew:false, inStock:true, rating:4.0, reviews:34 },
  { id:74, name:"Dash Digital", brand:"Dash", category:"digital", style:"digital", costPrice:300, sellPrice:600, images:["Dash_Digital_300.jpg","Dash_Digital_300_2.jpg"], description:"Sleek Dash digital watch with a clear display. Ideal for sports and outdoor activities.", featured:false, isNew:false, inStock:true, rating:4.1, reviews:52 },
  { id:75, name:"Loose Digital", brand:"Generic", category:"digital", style:"digital", costPrice:160, sellPrice:320, images:["Loose_Digital_160.jpg","Loose_Digital_160_2.jpg"], description:"Affordable digital watch with essential features. Simple and reliable for everyday use.", featured:false, isNew:false, inStock:true, rating:3.8, reviews:67 },
  { id:76, name:"ITAI Digital", brand:"ITAI", category:"digital", style:"digital", costPrice:300, sellPrice:600, images:["ITAI_Digital_300.jpg","ITAI_Digital_300_2.jpg","ITAI_Digital_300_3.jpg","ITAI_Digital_300_4.jpg","ITAI_Digital_300_5.jpg","ITAI_Digital_300_6.jpg","ITAI_Digital_300_7.jpg","ITAI_Digital_300_8.jpg","ITAI_Digital_300_9.jpg"], description:"Versatile ITAI digital watch in 9 designs. Alarm, stopwatch, and backlight functions included.", featured:false, isNew:false, inStock:true, rating:4.1, reviews:74 },
  { id:77, name:"Leather Folding Box", brand:"SS Collections", category:"accessories", style:"accessory", costPrice:200, sellPrice:400, images:["Leather_Folding_Box_200.jpg"], description:"Premium leather folding watch box. Elegant storage and gift presentation solution.", featured:false, isNew:false, inStock:true, rating:4.3, reviews:28 },
  { id:78, name:"Paper Love Box", brand:"SS Collections", category:"accessories", style:"accessory", costPrice:275, sellPrice:550, images:["Paper_Love_box_275.jpg"], description:"Decorative paper love watch gift box. Beautiful packaging for special occasions.", featured:false, isNew:false, inStock:true, rating:4.1, reviews:19 },
  { id:79, name:"Chain Cutter Tool", brand:"SS Collections", category:"accessories", style:"accessory", costPrice:275, sellPrice:550, images:["Chain_Cutter_275.jpg"], description:"Professional chain cutter tool for watch band adjustment. Essential watchmaker tool.", featured:false, isNew:false, inStock:true, rating:4.4, reviews:31 },
  { id:80, name:"Double Watch Stand", brand:"SS Collections", category:"accessories", style:"accessory", costPrice:70, sellPrice:140, images:["Double_Stand_70.jpg"], description:"Compact double watch display stand. Keeps your watches organized and easily accessible.", featured:false, isNew:false, inStock:true, rating:4.0, reviews:22 },
  { id:81, name:"Single Watch Stand", brand:"SS Collections", category:"accessories", style:"accessory", costPrice:60, sellPrice:120, images:["Single_Stand_60.jpg"], description:"Elegant single watch display stand. Perfect for showcasing your favourite timepiece.", featured:false, isNew:false, inStock:true, rating:4.0, reviews:18 },
  { id:82, name:"Rotating Watch Stand", brand:"SS Collections", category:"accessories", style:"accessory", costPrice:800, sellPrice:1600, images:["Rotate_Stand_800.jpg"], description:"Premium rotating watch display stand. Store and display multiple watches in style.", featured:false, isNew:false, inStock:true, rating:4.5, reviews:15 },
  { id:83, name:"Miracle Box Bag Set", brand:"Miracle", category:"accessories", style:"accessory", costPrice:1000, sellPrice:2000, images:["Miracle_Box_Bag_Set_1000.jpg"], description:"Luxury Miracle box and bag gift set. The premium gifting solution for watch enthusiasts.", featured:false, isNew:false, inStock:true, rating:4.6, reviews:24 },
  { id:84, name:"Coach Box Set", brand:"Coach", category:"accessories", style:"accessory", costPrice:600, sellPrice:1200, images:["Coach_Box_Set_600.jpg"], description:"Elegant Coach-branded watch gift box set. Premium packaging for special presentations.", featured:false, isNew:false, inStock:true, rating:4.4, reviews:29 },
  { id:85, name:"MK Box Set", brand:"MK", category:"accessories", style:"accessory", costPrice:600, sellPrice:1200, images:["MK_Box_Set_600.jpg"], description:"Stylish MK watch gift box set. Complete gifting package for the watch lover.", featured:false, isNew:false, inStock:true, rating:4.5, reviews:21 },
];

const CATEGORIES = [
  { id:'ladies',      name:'Ladies Watches', icon:'fa-venus',    image:'Omega_Ladies_086_1000.jpg', desc:'Elegant timepieces for her' },
  { id:'gents',       name:'Gents Watches',  icon:'fa-mars',     image:'Omega_Gents_086_1000.jpg',  desc:'Sophisticated watches for him' },
  { id:'digital',     name:'Digital Watches',icon:'fa-bolt',     image:'Lasika_Digital_325.jpg',     desc:'Smart digital timepieces' },
  { id:'accessories', name:'Accessories',    icon:'fa-box-open', image:'Coach_Box_Set_600.jpg',      desc:'Boxes, stands & tools' },
];

function getPriceDisplay(p) {
  if (p.sellPriceMax) return `NPR ${p.sellPrice.toLocaleString('en-IN')} – NPR ${p.sellPriceMax.toLocaleString('en-IN')}`;
  return `NPR ${p.sellPrice.toLocaleString('en-IN')}`;
}

function renderStars(r) {
  let s = '';
  for (let i = 1; i <= 5; i++) {
    if (i <= Math.floor(r)) s += '<i class="fas fa-star"></i>';
    else if (i - r < 1) s += '<i class="fas fa-star-half-alt"></i>';
    else s += '<i class="far fa-star"></i>';
  }
  return s;
}

const BRANDS = [...new Set(PRODUCTS.map(p => p.brand))].sort();
